src/Bigcommerce/Api/Client.php

BIG-15160: remove remaining setCipher() method

---

src/Bigcommerce/Api/Client.php

remove left over parameter for deleteAllCategories

---

src/Bigcommerce/Api/Client.php
test/Unit/Api/ClientTest.php

Adding coupon delete methods

---

src/Bigcommerce/Api/Client.php
test/Unit/Api/ClientTest.php

Adding deleteAllOrders and getOrderProductsCount

Adding deleteAllOrders and getOrderProductsCount

---

src/Bigcommerce/Api/Client.php
test/Unit/Api/ClientTest.php

- fix doc block
- fix incorrect coupon url and test
- add coupon count method
ping @lord2800 @bc-joshroe

BIG-16447: add coupon count method

---

src/Bigcommerce/Api/Client.php
src/Bigcommerce/Api/Connection.php
test/Unit/Api/ClientTest.php

Also...
More doc cleanup
Removed unused "isComplete" property
Split auth methods into basic and OAuth versions

Reimplementing PR 88 with corrections for underlying code drift

---

README.md

update readme to include oauth connection information

---

src/Bigcommerce/Api/Client.php

@bc-anna @philipmuir @bc-joshroe @bc-bfenton 
Doing this to enable tests against order status counts in the bcapp.

BIG-22012: add getOrderStatusesWithCounts

---

composer.json
src/Bigcommerce/Api/Resources/Sku.php
test/Unit/Api/Resources/SkuTest.php

Fix for https://github.com/bigcommerce/bigcommerce-api-php/issues/92
`Bigcommerce\Api\Client::getSkus()`
more tests here:
https://github.com/bigcommerce/bigcommerce/pull/12071
@aleachjr How do I change a version?
cc @bc-joshroe @lord2800 @becomevocal @ICarpenter @bc-AlyssNoland

API-16 fix for SkuOption error on Sku resource

---

src/Bigcommerce/Api/Client.php
src/Bigcommerce/Api/Resources/Currency.php
test/Unit/Api/ClientTest.php
test/Unit/Api/Resources/CurrencyTest.php

WIP
Please review @lord2800 @bc-bfenton 
SFO-MBP-ADRINEDA:bigcommerce-api-php ruth.adrineda$ composer test
> phpunit
PHPUnit 4.5.1 by Sebastian Bergmann and contributors.
Configuration read from /Users/ruth.adrineda/bc/bigcommerce-app-vm/codebases/bigcommerce-api-php/phpunit.xml.dist
The Xdebug extension is not loaded. No code coverage will be generated.
...............................................................  63 / 192 ( 32%)
............................................................... 126 / 192 ( 65%)
............................................................... 189 / 192 ( 98%)
...
Time: 486 ms, Memory: 11.00Mb
OK (192 tests, 341 assertions)
SFO-MBP-ADRINEDA:bigcommerce-api-php ruth.adrineda$

OMNI-1024 Expose currencies v2 resource to Client API

---

src/Bigcommerce/Api/Connection.php

Simple fix for STDIN #139 issue

fixed typo RE: #139

---

src/Bigcommerce/Api/Client.php
src/Bigcommerce/Api/Resources/ProductImage.php
test/Unit/Api/ClientTest.php
test/Unit/Api/Resources/ProductImageTest.php

Please review @bc-bfenton @lord2800 @ICarpenter @aleachjr

OMNI-1259 Expose product image resource to Client API

---

src/Bigcommerce/Api/Resources/Customer.php

As it says on the tin.
Ping @mattolson @bc-bfenton @ICarpenter
cc @bc-AlyssNoland @bookernath

BIG-27111 Fix a method call name due to a refactor

---

src/Bigcommerce/Api/Client.php
src/Bigcommerce/Api/Resources/Page.php
test/Unit/Api/ClientTest.php
test/Unit/Api/Resources/PageTest.php

Functionality for Web Content API. Ability to get, create, update and delete pages under the "Storefront Content > Web Pages" menu in the CP
@aleachjr @lord2800 @bc-joshroe @ICarpenter

WEB-299: Web Content API Client Endpoints

---

src/Bigcommerce/Api/Client.php
test/Unit/Api/ClientTest.php

BIG-16297 - Adding some methods to the API Client

BIG-16297 - Adding some methods to the API Client

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Ticket: 
- [API-918](https://jira.bigcommerce.com/browse/API-918)
Added issue template, pr template, and contributing guidelines

API-918: Add contribution guidelines and templates

---

src/Bigcommerce/Api/Client.php

Added webhooks with DocBlocks (needs tests really) based on #101 updated to get rid of merge conflicts

Ported Webhooks from #101

---

composer.json

After some testing, this package seems to work fine with PHP-JWT v5.0.

Support newer versions of firebase/php-jwt

---

composer.json
phpunit.xml.dist

upgrade `phpunit` to 4.8 version (latest 4.x branch), upgrade `php-coveralls` to latest version (2.1).

upgrade phpunit to 4.8 version

---

src/Bigcommerce/Api/Client.php
src/Bigcommerce/Api/Connection.php
src/Bigcommerce/Api/Filter.php
src/Bigcommerce/Api/Resource.php

some phpdoc and other minor fixes

some phpdoc and other minor fixes

---

src/Bigcommerce/Api/Resources/Category.php
test/Unit/Api/Resources/CategoryTest.php

Implements delete test for API. Serves no other purpose
https://developer.bigcommerce.com/api/v2/#delete-a-category

Added Delete test to categories

---

README.md

Fix typo: Add the closing single quotation mark

Update OAuth code sample in README.md

---

test/Unit/Api/ClientErrorTest.php
test/Unit/Api/ConnectionTest.php
test/Unit/Api/ErrorTest.php
test/Unit/Api/FilterTest.php
test/Unit/Api/NetworkErrorTest.php
test/Unit/Api/ServerErrorTest.php

This PR fixes the PSR4 namespace issues with the tests mentioned here #268

Fix for PSR4 namespace issues in Tests

---

src/Bigcommerce/Api/Client.php

+ Delete the given optionValue
+ Return the collection of all option values By OptionID
+ Get collection of product rules by Product

Improvements

---

composer.json
phpunit.xml.dist
src/Bigcommerce/Api/Client.php
src/Bigcommerce/Api/Connection.php
test/Unit/Api/ClientTest.php
test/Unit/Api/ConnectionTest.php
test/Unit/Api/Resources/ProductTest.php
test/Unit/Api/Resources/ResourceTestBase.php
test/Unit/Api/Resources/RuleTest.php

- Fix deprecation warning
`Deprecated: Use of "self" in callables is deprecated in bigcommerce-api-php/src/Bigcommerce/Api/Client.php on line 356`
- Upgrade PHPUnit
ping @bigcommerce/php

Fix deprecation warning and upgrade PHPUnit

---

src/Bigcommerce/Api/Client.php

Fix `Bigcommerce::getProductImages(..);`
Currently it always returns `false`
Add links to any relevant tickets and documentation.
- #284

Fix the get product images path

---

.circleci/config.yml
test/Unit/Api/ClientTest.php

Add CircleCI config
So we have CI running against this
ping @bigcommerce/php

Add CircleCI config

---

.circleci/config.yml
.gitignore
.phpstan/baseline.neon
CONTRIBUTING.md
composer.json
phpstan.neon.dist
src/Bigcommerce/Api/Client.php
src/Bigcommerce/Api/Connection.php

Check code with [phpstan](https://phpstan.org/)
By default, all current errors are suppressed.
We start from [level 6](https://phpstan.org/user-guide/rule-levels) and in the future may rise a bar.
See circle.
This tool is used only in the CI environment and should not affect production.
PhpStan [documentation](https://phpstan.org/user-guide/getting-started)

PHPMNT-8 Add phpstan

---

.phpstan/baseline.neon
src/Bigcommerce/Api/Client.php
test/Unit/Api/ClientTest.php

Fix Client::getTime()

---

.phpstan/baseline.neon
src/Bigcommerce/Api/Client.php
src/Bigcommerce/Api/Connection.php
src/Bigcommerce/Api/Resource.php
src/Bigcommerce/Api/Resources/Brand.php
src/Bigcommerce/Api/Resources/Category.php
src/Bigcommerce/Api/Resources/Coupon.php
src/Bigcommerce/Api/Resources/Currency.php
src/Bigcommerce/Api/Resources/Customer.php
src/Bigcommerce/Api/Resources/Option.php
src/Bigcommerce/Api/Resources/OptionSet.php
src/Bigcommerce/Api/Resources/OptionSetOption.php
src/Bigcommerce/Api/Resources/OptionValue.php
src/Bigcommerce/Api/Resources/Order.php
src/Bigcommerce/Api/Resources/Sku.php
src/Bigcommerce/Api/Resources/SkuOption.php
test/Unit/Api/ClientTest.php

- Fix phpstan violations
- Regenerate baseline
First step to reduce phpstan violations

Fix various codestyle issues

---

.circleci/config.yml

Run CI against PHP 8.3
✅ CI on this PR

Run CI against PHP 8.3

---

.circleci/config.yml
composer.json
src/Bigcommerce/Api/Client.php
src/Bigcommerce/Api/Connection.php

Add PHP 8.4 to CircleCI matrix
PHPMNT-177
CI on this PR should suffice

chore(platform): PHPMNT-177 Add PHP 8.4 to CircleCI matrix

---

src/Bigcommerce/Api/Connection.php

Add a `getHeadersList()` method to the `Connection` class to allow returning a list of all response headers, including headers with duplicate keys.
The existing `getHeaders()` method and process for generating those headers will overwrite response headers that share the same key name leaving only the last one. This has become a problem in many of our tests where we depend on the `Set-Cookie` response header to retrieve an `XSRF-TOKEN` cookie.  We have found that responses with multiple `Set-Cookie` response headers are not reliably making the `XSRF-TOKEN` cookie available as it gets overwritten by another `Set-Cookie` header.
This change is meant to be additive and not alter the output of any existing methods.
- https://bigcommercecloud.atlassian.net/browse/STRF-13001
Here is a live …

STRF-13001 - Add Method for Retrieving All Response Headers Including Duplicates
