bigcommerce/bigcommerce-api-php

src/Bigcommerce/Api/Client.php
test/Unit/Api/ClientTest.php

Adding getOrderStatus and fixing the client library to use 'order_statuses' instead of 'orderstatuses'.

Adding getOrderStatus

---

src/Bigcommerce/Api/Client.php
test/Unit/Api/ClientTest.php

Adding Order Shipment and Shipping Address methods
Should fix this logged issue:
https://github.com/bigcommerce/bigcommerce-api-php/issues/9

Adding Order Shipment and Shipping Address methods

---

src/Bigcommerce/Api/Connection.php

BIG-17565 Add function to remove a header from Connection object.

---

src/Bigcommerce/Api/Connection.php

Else case to switch content type and "use raw" back to JSON-based settings.
Inability to turn this off was hindering functional testing.

API-94 - adding else case to switch back to JSON mode if useXml is false

---

.travis.yml

I pull this down and ran phpunit with php7 and it ran swimmingly. Lets see if travis likes it.

Add php7 to travis.yml

---

src/Bigcommerce/Api/Connection.php

…e away, resetting to default
@aleachjr @PascalZajac 
What:
Reverting https://github.com/bigcommerce/bigcommerce-api-php/pull/155
and optionally define STDIN to address issues mentioned in same PR ^
Why:
Breaking basic tests
curl_exec(): CURLOPT_INFILE resource has gone away, resetting to default
FAILURES!
Tests: 70, Assertions: 476, Errors: 12.
Testing:
................................................................. 65 / 70 ( 92%)
.....
OK (70 tests, 541 assertions)

Revert https://github.com/bigcommerce/bigcommerce-api-php/pull/155

---

composer.json
src/Bigcommerce/Api/Client.php
src/Bigcommerce/Api/Resources/Customer.php
test/Unit/Api/ClientTest.php

Add support for the new customer login token generation mechanism.
Allow users to generate customer login tokens for SSO.
Because of the way the login mechanism works, a new optional configuration parameter called `client_secret` has been added. In order to generate login tokens, you must also have the "customer login" scope. This will be checked server side, so even if you attempt to generate tokens, they will be rejected so long as your credentials don't have the correct scopes.
@aleachjr @ICarpenter @bc-bfenton 
cc @bc-AlyssNoland @bookernath

BIG-27111 Support for retrieving the customer login token

---

src/Bigcommerce/Api/Connection.php

http://www.jasperstudios.com/bigcommerce-api-code-patch/
> Namely, the biggest issue was that the official version did not properly handle the private CURL member object.  The CURL object referenced inside the big-commerce.php class is being reused in the POST, PUT, DELETE, and GET methods, and, after the use of each method the CURL member object simply was not being reset correctly.  More specifically, before it re-uses the CURL object for another call under the same initialization settings, it needed to reset old state flags.
> 
> Another issue we discovered was that API calls to the class involving the underlying PUT request was not properly closing a temporary file that had been opened just a few lines earlier.
> 
> The consequences of these bugs when attempting to make concurrent and …

Updated connection.php with Jasper Studios fixes to resolve deadlocking

---

src/Bigcommerce/Api/Connection.php

**What?**
I am changing a PHP cURL setting so that requests made will include an 'Accept-Encoding' header with 'gzip' as one of it's accepted encodings.  This also allows the PHP cURL library to respect the 'Content-Encoding' response header and decode a 'gzip' response.
This change only effects people using oAuth credentials.
**Why?**
The purpose is to make the PHP API Library utilize gzip responses from our server without changing the way a Dev makes use of the library methods and classes.
**Testing/proof?**
When using the API library use the following code block after making a request to view it's response headers:
```
$r_headers = Bigcommerce::getConnection()->getHeaders();
foreach($r_headers as $key => $value){
echo "<p>" . $key . ": " . $value . "</p>";
}
``` 
You will see that, …

API-644 - Adding gzip support using the CURLOPT_ENCODING option

---

README.md
src/Bigcommerce/Api/Client.php

Adding instructions on how to get the Auth Token when using OAuth and the SDK.
Remove the useUrlEncoded call when making getAuthToken as it results in passing the wrong content type to the API call.

Fix the get auth token and update the README

---

src/Bigcommerce/Api/Client.php
src/Bigcommerce/Api/Resources/ShippingMethod.php
src/Bigcommerce/Api/Resources/ShippingZone.php
test/Unit/Api/Resources/ShippingMethodTest.php
test/Unit/Api/Resources/ShippingZoneTest.php

Added support for shipping api V2 to:
- zones
- methods (static and real-time)
These resources allow stores to manage shipping configurations
For more details refer to API v2 doc https://developer.bigcommerce.com/api/v2/#api-v2-documentation and tickets mentioned below
- https://jira.bigcommerce.com/browse/PROJECT-1430
- https://jira.bigcommerce.com/browse/SHIPPING-8

Add shipping zone and method to client api

---

composer.json

Allows `paragonie/random_compat: ~1.4|~2.0` instead of locking to `~2.0`. This is done for compatibility with other packages that require `~1.4`. All `2.0` updates are back-ported to `1.4`, so this should not cause any issues.
See the "Version Conflict with [Other PHP Project]" section in the `paragonie/random_compat` [README.](https://github.com/paragonie/random_compat#troubleshooting)

require paragonie/random_compat '~1.4|~2.0'

---

test/Unit/Api/ClientTest.php

Fix the `Client::getTime` test to use timestamps, rather than comparing `DateTime` objects.

Fix the time test to compare the timestamps directly

---

.travis.yml
README.md
composer.json

PHP 7.0 is the lowest supported version these days: http://php.net/supported-versions.php
Therefore, I've updated readmes and other things to remove support for anything lower.
I've also added 7.1 and 7.2 to Travis so we can start testing for compatibility with modern versions.

Bump min PHP to 7.0, start running tests on 7.1 and 7.2

---

composer.json

https://github.com/paragonie/random_compat needs only for php 5.x versions.
but `bigcommerce-api-php` requires php 7.x
php 7 no need polyfill (http://php.net/manual/en/book.csprng.php)

random_compat needs only for php 5.x

---

src/Bigcommerce/Api/Client.php

Get collection of product skus by Product

getSkusByProduct 

---

src/Bigcommerce/Api/Client.php
test/Unit/Api/ClientTest.php

removed trailing '/' from endpoint for getProductCustomFields() resulting in a 401 response
[#234 "401 response when calling getProductCustomFields()"](https://github.com/bigcommerce/bigcommerce-api-php/issues/234)

update getProductCustomFields() endpoint

---

src/Bigcommerce/Api/Client.php
test/Unit/Api/Resources/ShippingZoneTest.php

removed trailing '/' from endpoint for getShippingZones() resulting in a 401 response
[#232 "401 response when calling getShippingZones()"](https://github.com/bigcommerce/bigcommerce-api-php/issues/232)

update endpoint for getShippingZones()

---

src/Bigcommerce/Api/Client.php
test/Unit/Api/ClientTest.php

Fixed product custom field methods to use the correct v2 endpoints. `/customfields/` gives a 401 status code. The documentation uses `/custom_fields`. It should be noted that `/customfields` (no trailing slash) returns a 200 status code.
Add links to any relevant tickets and documentation.
- [BC custom field documentation](https://developer.bigcommerce.com/api/v2/#list-custom-fields)
NA

Use product custom fields endpoints form official documentation to stop random 401 status codes. 

---

src/Bigcommerce/Api/Connection.php

On certain BigCommerce stores, getHeader fails because the X-BC-ApiLimit-Remaining header is all lower-case in the HTTP response.  This causes getRequestsRemaining to always return 0 and puts the code into an infinite wait for more requests.  Instead, change getHeader to do a case-insensitive search for the header if the exact case is not found.  Please merge this into the trunk.  The code keeps breaking every time I update the library.
I had created a previous pull request to fix this, but I don't think it got fixed:
https://github.com/bigcommerce/bigcommerce-api-php/pull/196

Fix getHeader to be case-insensitive

---

src/Bigcommerce/Api/Connection.php

User agent is no longer present when making the requests, this causes some
of them to fail
Before: 
After:
@bigcommerce/husky

fix(curl): Add CURLOPT_USERAGENT to all requests

---

.phpstan/baseline.neon
composer.json
src/Bigcommerce/Api/Client.php
test/Unit/Api/ClientTest.php

- Adds the ability to override `api_url` and `login_url` as part of the oAuth flow.
- Removes the stale codeless/jugglecode dependency as it seems it no longer exists and composer fails trying to fetch it (https://github.com/codeless/JuggleCode is a 404)
- phpstan was complaining about a few things in the file I edited, so I tweaked some type docs to fix it, which in turn made some of the baseline neon definitions not applicable anymore. Seems reasonable to me, but LMK if a preferred method exists
No screenshots to attach, but I have tested these changes in my consumer app via `composer require "bigcommerce/api @dev"` and verified the right URLs are being used:
If no custom URLs are provided, `https://api.bigcommerce.com` and `https://login.bigcommerce.com` are used.
If custom URLs are …

Add api_url and login_url config options

---

README.md
src/Bigcommerce/Api/Client.php
test/Unit/Api/ClientTest.php

Fixes #298
- Updates Client::getTime() to expect time in milliseconds as that's [the response from /time](https://api.bigcommerce.com/time)
- Adds Client::getStoreTime() which queries https://api.bigcommerce.com/stores/{{storeHash}}/v2/time. That requires authentication so this method can be used to verify that the client is configured correctly
- Update README to reflect changes
_**Updated `::getTime()`**_
I've updated the unit test to reflect what's actually returned by the API. Also I've run the steps provided to reproduce this issue, verifying that it no longer happens:
```
php > var_dump(\Bigcommerce\Api\Client::getTime());
php shell code:1:
class DateTime#6 (3) {
public $date =>
string(26) "2024-06-13 13:43:56.124000"
public $timezone_type =>
int(1)
public $timezone =>
string(6) …
```

Fix Client::getTime()
